teacher = User.create!(first_name: "kajetanTeacher", last_name: "jankowski", email: "kajetan@test.com", password: "123456", role: "teacher")
student = User.create!(first_name: "kajetanStudent", last_name: "jankowski", email: "jankowski@test.com", password: "123456", role: "student")
course = Course.create!(name: "Informatyka", code: "INF101", teacher: teacher)
sc = StudentCourse.create!(student: student, course: course)
Grade.create!(student_course: sc, value: 5)
